# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Web

on:
  push:
    branches: [ master ]
    #paths: ['lib/**','example/lib/**','pubspec.yaml','example/pubspec.yaml']
jobs:
  web_build_and_deploy:
    name: Example Web Page
    env:
      my_secret: ${{secrets.COMMIT_SECRET}}
    runs-on: macos-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
      - name: "Web Build 🔧"
        run: |
          cd example
          flutter pub get
          flutter build web --web-renderer canvaskit --release --base-href="/FlutterUI/" --dart-define=FLUTTER_WEB_CANVASKIT_URL=https://cdn.jsdelivr.net/npm/canvaskit-wasm@0.33.0/bin/
      - name: "Web Deploy 🚀"
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: '${{ secrets.COMMIT_SECRET }}'
          branch: gh-pages
          folder: example/build/web
