# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Web

on:
  push:
    branches: [ master ]
jobs:
  web_build_and_deploy:
    name: Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: macos-latest

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.0'
          channel: 'stable'
      - name: "Web Build 🔧"
        run: |
          cd example
          flutter pub get
          flutter build web --web-renderer canvaskit --release
      - name: "Web Deploy 🚀"
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: '${{ secrets.commit_secret }}'
          branch: gh-pages
          folder: example/build/web
